name: Convert PDF to Word

on:
  workflow_dispatch:  # Запуск вручную из вкладки Actions
  issues:
    types: [opened, labeled]

jobs:
  convert:
    if: contains(github.event.issue.labels.*.name, 'convert')
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Даем разрешение на редактирование Issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pygithub

      - name: Run conversion script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONVERTAPI_SECRET: ${{ secrets.CONVERTAPI_SECRET }}
        run: python .github/scripts/convert.py "${{ github.event.issue.number }}"
